version: "3.7"

services:

  backend:
    image: kondrahin/punk_events_backend:latest
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - punkeventsnetwork
    restart: always

  frontend:
    image: kondrahin/punk_events_frontend:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - punkeventsnetwork

  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/scripts/pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - punkeventsnetwork

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - punkeventsnetwork

volumes:
  postgres_data: null
  redis-data: null
  redis.conf:

    null
networks:
  punkeventsnetwork:
    driver: bridge
