name: Styles

on: push

jobs:
  styles:
    name: Styles
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache python packages
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-python-packages
        with:
          path: .venv
          key: ${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        shell: bash
        run: |
            cd backend
            python -m venv .venv
            source .venv/bin/activate
            pip install poetry==1.1.6
            poetry config virtualenvs.in-project true
            poetry install

      - name: Run lint
        run: |
          cd backend
          source .venv/bin/activate
          ./scripts/lint
